# This is a comment

##########################################################################
#   DEFAULT PARAMETERS FOR DETECTOR COSTRUCTION                          #
#  --------------------------------------------------------------------  #
#   This is a configuration file for detector costruction parameters,    #
#   it's suggested to copy this file to recreate a new custom            #
#   config file.                                                         #
#   The complete list of the following keywords with their meanings is   #
#   in 'docs/configuration.md'.                                          #
##########################################################################

# Vessel's dimentions
gas_length = 17.0 m
gas_radius = 1.75 m

# Mirror's dimentions
mirror_curvature_radius = 34.0 m

mirror_outer_radius    = 1.7 m
mirror_inner_radius    = 12.0 cm
mirror_thickness      = 2.5 cm

mirror_position_z      = 8.5 m

# PMT's and Disks' dimensions
PMT_radius     = 7.8 mm
disk_radius    = 30.0 cm

disk_thick     = 1.0 mm

disk_position_z = -8.5 m
disk_position_r = 85 cm

# Materials
world_material  = G4_Galactic
gas_material    = G4_Ne
mirror_material = G4_GLASS_PLATE
PMT_material    = G4_SILICON_DIOXIDE

# Optical properties for materials
gas_photon_energies  = 1.907 eV, 2.066 eV, 2.254 eV, 2.480 eV, 2.755 eV, 2.952 eV, 3.100 eV, 3.263 eV, 3.542 eV, 4.133 eV, 4.959 eV, 5.510 eV, 6.199 eV, 6.358 eV
gas_refractive_index = 1.00006117, 1.00006124, 1.00006134, 1.00006146, 1.00006164, 1.00006177, 1.00006188, 1.00006201, 1.00006224, 1.00006280, 1.00006376, 1.00006451, 1.00006561, 1.00006588

mirror_photon_energies = 1.907 eV, 6.358 eV
mirror_reflectivity   = 0.9, 0.9

PMT_photon_energies = 1.907 eV, 1.937 eV, 1.968 eV, 2.000 eV, 2.033 eV, 2.066 eV, 2.101 eV, 2.138 eV, 2.175 eV, 2.214 eV, 2.254 eV, 2.296 eV, 2.339 eV, 2.384 eV, 2.431 eV, 2.480 eV, 2.530 eV, 2.583 eV, 2.638 eV, 2.695 eV, 2.755 eV, 2.818 eV, 2.883 eV, 2.952 eV, 3.024 eV, 3.100 eV, 3.179 eV, 3.263 eV, 3.351 eV, 3.444 eV, 3.542 eV, 3.647 eV, 3.757 eV, 3.875 eV, 3.999 eV, 4.133 eV, 4.275 eV, 4.428 eV, 4.592 eV, 4.769 eV, 4.959 eV, 5.166 eV, 5.391 eV, 5.635 eV, 5.904 eV, 6.199 eV, 6.525 eV
PMT_efficiency = 0.000, 0.000, 0.001, 0.002, 0.004, 0.007, 0.012, 0.018, 0.025, 0.033, 0.044, 0.058, 0.074, 0.090, 0.106, 0.121, 0.135, 0.148, 0.159, 0.168, 0.174, 0.180, 0.185, 0.189, 0.193, 0.197, 0.200, 0.203, 0.204, 0.202, 0.200, 0.197, 0.194, 0.191, 0.188, 0.184, 0.175, 0.162, 0.147, 0.129, 0.115, 0.104, 0.097, 0.091, 0.075, 0.061, 0.028