# This is a comment

##########################################################################
#   DEFAULT PARAMETERS FOR DETECTOR COSTRUCTION                          #
#  --------------------------------------------------------------------  #
#   This is a configuration file for detector costruction parameters,    #
#   it's suggested to copy this file to recreate a new custom            #
#   config file.                                                         #
#   The complete list of the following keywords with their meanings is   #
#   in 'docs/configuration_files.md'.                                    #
##########################################################################

# Vessel's dimentions
gasLength = 17.0 m
gasRadius = 1.75 m

# Mirror's dimentions
mirrorCurvatureRadius = 34.0 m

mirrorOuterRadius    = 1.7 m
mirrorInnerRadius    = 12.0 cm
mirrorThickness      = 2.5 cm

mirrorPositionZ      = 8.5 m

# PMT's and Disks' dimensions
PMTradius     = 7.8 mm
diskRadius    = 30.0 cm

diskThick     = 1.0 mm

diskPositionZ = -8.5 m
diskPositionR = 85 cm

# Materials
worldMaterial  = G4_Galactic
gasMaterial    = G4_Ne
mirrorMaterial = G4_GLASS_PLATE
PMTmaterial    = G4_SILICON_DIOXIDE

# Optical properties for materials
neonPhotonEnergies  = 1.907 eV, 2.066 eV, 2.254 eV, 2.480 eV, 2.755 eV, 2.952 eV, 3.100 eV, 3.263 eV, 3.542 eV, 4.133 eV, 4.959 eV, 5.510 eV, 6.199 eV, 6.358 eV
neonRefractiveIndex = 1.00006117, 1.00006124, 1.00006134, 1.00006146, 1.00006164, 1.00006177, 1.00006188, 1.00006201, 1.00006224, 1.00006280, 1.00006376, 1.00006451, 1.00006561, 1.00006588

mirrorPhotonEnergies = 1.907 eV, 6.358 eV
mirrorReflectivity   = 0.9, 0.9

PMTphotonEnergies = 1.907 eV, 2.066 eV, 2.254 eV, 2.480 eV, 2.755 eV, 2.952 eV, 3.100 eV, 3.263 eV, 3.542 eV, 4.133 eV, 4.959 eV, 5.510 eV, 6.199 eV, 6.702 eV
PMTefficiency = 0.0, 0.01, 0.045, 0.11, 0.17, 0.195, 0.195, 0.19, 0.175, 0.145, 0.115, 0.09, 0.065, 0
