# This is a comment

##########################################################################
#   DEFAULT PARAMETERS FOR DETECTOR COSTRUCTION                          #
#  --------------------------------------------------------------------  #
#   This is a configuration file for detector costruction parameters,    #
#   it's suggested to copy this file to recreate a new custom            #
#   config file.                                                         #
#   The complete list of the following keywords with their meanings is   #
#   in 'docs/configuration.md'.                                          #
##########################################################################

# Vessel's dimentions
ga_length = 17.0 m
gas_radius = 1.75 m

# Mirror's dimentions
mirror_curvature_radius = 34.0 m

mirror_outer_radius    = 1.7 m
mirror_inner_radius    = 12.0 cm
mirror_thickness      = 2.5 cm

mirror_position_z      = 8.5 m

# PMT's and Disks' dimensions
PMT_radius     = 7.8 mm
disk_radius    = 30.0 cm

disk_thick     = 1.0 mm

disk_position_z = -8.5 m
disk_position_r = 85 cm

# Materials
world_material  = G4_Galactic
gas_material    = G4_Ne
mirror_material = G4_GLASS_PLATE
PMT_material    = G4_SILICON_DIOXIDE

# Optical properties for materials
gas_photon_energies  = 1.907 eV, 2.066 eV, 2.254 eV, 2.480 eV, 2.755 eV, 2.952 eV, 3.100 eV, 3.263 eV, 3.542 eV, 4.133 eV, 4.959 eV, 5.510 eV, 6.199 eV, 6.358 eV
gas_refractive_index = 1.00006117, 1.00006124, 1.00006134, 1.00006146, 1.00006164, 1.00006177, 1.00006188, 1.00006201, 1.00006224, 1.00006280, 1.00006376, 1.00006451, 1.00006561, 1.00006588

mirror_photon_energies = 1.907 eV, 6.358 eV
mirror_reflectivity   = 0.9, 0.9

PMT_photon_energies = 1.907 eV, 2.066 eV, 2.254 eV, 2.480 eV, 2.755 eV, 2.952 eV, 3.100 eV, 3.263 eV, 3.542 eV, 4.133 eV, 4.959 eV, 5.510 eV, 6.199 eV, 6.702 eV
PMT_efficiency = 0.0, 0.01, 0.045, 0.11, 0.17, 0.195, 0.195, 0.19, 0.175, 0.145, 0.115, 0.09, 0.065, 0
